### ISSUE TITLE
Kitsunebi的URL生成规则文档

### ISSUE THREAD

**Issue by sabersalv** [eycorsican/kits-faq#1]
我正在写一个[自动安装项目](https://github.com/StreisandEffect/discussions/issues/85#issuecomment-381918385), 需要生成URLl和QR Code. V2ray没有官方URL定义, 每个App又是用不一样的方法实现.

请问, 哪里可以查看到URL生成的规则文档?

**Comment by eycorsican** [comment]
@sabersalv 抱歉，我现在才看到，如果还不算太晚的话，我把 URL 的格式放到 FAQ 里面了，可以在这里查看：https://eycorsican.github.io/kits-faq/
